// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8KG9A1WT2sKDoiM1oEZqRD
// Component: J_gSc0trxmCUlm
import * as React from "react";

import { Link, GatsbyLinkProps as LinkProps } from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 1I0X6KlI9K7MqZ/component

import "@plasmicapp/react-web/lib/plasmic.css";

import * as plasmic_new_habistack_com_css from "../new_habistack_com/plasmic_new_habistack_com.module.css"; // plasmic-import: rcEGNgTfxT6W6gDjnxsJgN/projectcss
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as plasmic_habistack_marketing_css from "../habistack_marketing/plasmic_habistack_marketing.module.css"; // plasmic-import: cEHjHBABazmDxgQhPGAjL/projectcss
import * as projectcss from "./plasmic_jeremy_copy_of_fathym_platform_marketing.module.css"; // plasmic-import: 8KG9A1WT2sKDoiM1oEZqRD/projectcss
import * as sty from "./PlasmicSolutions.module.css"; // plasmic-import: J_gSc0trxmCUlm/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: shMcYoVXVXVdVc/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: 7yC5yf_u7zQ0YY/icon
import logisticsCardpngWoDgFhz86DuiEm from "./images/logisticsCardpng.png"; // plasmic-import: WODgFHZ86duiEm/picture
import eventCardpng2IHw6X8TbBKuPy from "./images/eventCardpng.png"; // plasmic-import: 2iHW6x8TbBKuPy/picture
import movementCardpng6SL4KxuuRiJnlQ from "./images/movementCardpng.png"; // plasmic-import: 6sL4KXUURiJnlQ/picture
import agricultureCardpngEGEfukgqcRCtAw from "./images/agricultureCardpng.png"; // plasmic-import: eGEfukgqcRCtAw/picture
import energyCardpngMCep0OcxosRPe from "./images/energyCardpng.png"; // plasmic-import: M-Cep0OcxosRPe/picture
import droneCardpngYBkG2JwOx0Isiu from "./images/droneCardpng.png"; // plasmic-import: YBkG2JWOx0isiu/picture

export type PlasmicSolutions__VariantMembers = {};
export type PlasmicSolutions__VariantsArgs = {};
type VariantPropType = keyof PlasmicSolutions__VariantsArgs;
export const PlasmicSolutions__VariantProps = new Array<VariantPropType>();

export type PlasmicSolutions__ArgsType = {};
type ArgPropType = keyof PlasmicSolutions__ArgsType;
export const PlasmicSolutions__ArgProps = new Array<ArgPropType>();

export type PlasmicSolutions__OverridesType = {
  root?: p.Flex<"section">;
  h2?: p.Flex<"h2">;
};

export interface DefaultSolutionsProps {
  className?: string;
}

function PlasmicSolutions__RenderFunc(props: {
  variants: PlasmicSolutions__VariantsArgs;
  args: PlasmicSolutions__ArgsType;
  overrides: PlasmicSolutions__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_new_habistack_com_css.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        plasmic_habistack_marketing_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__rmFv2)}>
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2
          )}
        >
          {"This text was changed for the platform page"}
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__g7Kff
          )}
        >
          {
            "Bringing overwhelming technology to even the most basic of competitive battles,\nour data can solve your problems today."
          }
        </div>

        <div className={classNames(projectcss.all, sty.columns__p5CfW)}>
          <div className={classNames(projectcss.all, sty.column__cVYm0)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___55Ug)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: logisticsCardpngWoDgFhz86DuiEm,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns___6Tba)}>
              <div className={classNames(projectcss.all, sty.column___58Si6)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___1APw3
                  )}
                >
                  {"Logistics"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__njs0G
                  )}
                >
                  {"Supply Chain"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cG0F
                  )}
                >
                  {
                    "Choke points and bottle necks don't need unexpected interruptions. Much more than alerts, this is integrated intelligence.\n"
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__by8MO)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg___10MtF)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__laIf
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__vW8Dq)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__pjb6)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: eventCardpng2IHw6X8TbBKuPy,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__kcHaP)}>
              <div className={classNames(projectcss.all, sty.column__oMgr)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___20Eyu
                  )}
                >
                  {"Events"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kXlcj
                  )}
                >
                  {"Concerts & Sports"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1ZWbT
                  )}
                >
                  {
                    "Corridors flooded with people? Let's make sure rain and floods don't interrupt. With our help the show will go on.\n"
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__o30Kd)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__v4Lt2)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oSeeR
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__fGiJy)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__w5Je6)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: movementCardpng6SL4KxuuRiJnlQ,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__jcgoy)}>
              <div className={classNames(projectcss.all, sty.column__hhg7S)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__cjVz0
                  )}
                >
                  {"Movement"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s1Xx
                  )}
                >
                  {"Transportation"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5D3Xq
                  )}
                >
                  {
                    "The wheel might be where it all started but it's not where we're going. Now we need real intelligent tech to keep everything rolling."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__qkVjD)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg___0JvBl)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kt0V3
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>

        <div className={classNames(projectcss.all, sty.columns___9OWGt)}>
          <div className={classNames(projectcss.all, sty.column__iL9X)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__nhh1E)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: agricultureCardpngEGEfukgqcRCtAw,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__g5Fp0)}>
              <div className={classNames(projectcss.all, sty.column__ubpBq)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__a63RE
                  )}
                >
                  {"Resources"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mmo8
                  )}
                >
                  {"Agriculture & Mining"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__p0CuO
                  )}
                >
                  {
                    "Money doesn't grow on trees but it'll certainly fall off of them if they don't make it through the storm. We also help with gold digging. ;)"
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__g7Kmo)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__gBd6T)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wAeOf
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__ap22)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__mX5PK)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: energyCardpngMCep0OcxosRPe,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__dcryd)}>
              <div className={classNames(projectcss.all, sty.column__ritxm)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__fIlbB
                  )}
                >
                  {"Energy"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xIsyV
                  )}
                >
                  {"Energy Outlook"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__r2MMv
                  )}
                >
                  {
                    "Solar. Wind. Rain. Fire. The elements may help us make power but they can also disrupt its generation. We keep eyes on it.\n"
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__vXjCx)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__soxqS)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yWj36
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__nfOfT)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__uWhZq)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: droneCardpngYBkG2JwOx0Isiu,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__g2GBj)}>
              <div className={classNames(projectcss.all, sty.column__pQhip)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__qOuc4
                  )}
                >
                  {"Robots"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6Wpjj
                  )}
                >
                  {"They're Coming"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ee5WG
                  )}
                >
                  {
                    "They're here today. Drones and self-driving vehicles may be getting smarter but they still need help navigating the weather."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__y4Ttl)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__nIh97)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kJx3Y
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSolutions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSolutions__VariantsArgs;
    args?: PlasmicSolutions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSolutions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSolutions__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSolutions__ArgProps,
          internalVariantPropNames: PlasmicSolutions__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSolutions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSolutions";
  } else {
    func.displayName = `PlasmicSolutions.${nodeName}`;
  }
  return func;
}

export const PlasmicSolutions = Object.assign(
  // Top-level PlasmicSolutions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicSolutions
    internalVariantProps: PlasmicSolutions__VariantProps,
    internalArgProps: PlasmicSolutions__ArgProps
  }
);

export default PlasmicSolutions;
/* prettier-ignore-end */
