// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8KG9A1WT2sKDoiM1oEZqRD
// Component: QFFPb6q_FEOUzp
import * as React from "react";

import { Link, GatsbyLinkProps as LinkProps } from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 1I0X6KlI9K7MqZ/component

import "@plasmicapp/react-web/lib/plasmic.css";

import * as plasmic_new_habistack_com_css from "../new_habistack_com/plasmic_new_habistack_com.module.css"; // plasmic-import: rcEGNgTfxT6W6gDjnxsJgN/projectcss
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as plasmic_habistack_marketing_css from "../habistack_marketing/plasmic_habistack_marketing.module.css"; // plasmic-import: cEHjHBABazmDxgQhPGAjL/projectcss
import * as projectcss from "./plasmic_jeremy_copy_of_fathym_platform_marketing.module.css"; // plasmic-import: 8KG9A1WT2sKDoiM1oEZqRD/projectcss
import * as sty from "./PlasmicTechnology.module.css"; // plasmic-import: QFFPb6q_FEOUzp/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: shMcYoVXVXVdVc/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: 7yC5yf_u7zQ0YY/icon
import microsoftTeamsImage22PngFCmD4ZxRorQbig from "./images/microsoftTeamsImage22Png.png"; // plasmic-import: FCmD4ZxRORQbig/picture
import microsoftTeamsImage21PngJRtiyJu3WvOq3A from "./images/microsoftTeamsImage21Png.png"; // plasmic-import: JRtiyJU3wvOq3A/picture
import multiDatapngHM7CYgdgjrHxY from "./images/multiDatapng.png"; // plasmic-import: hM7CYgdgjr-HxY/picture
import cloudNativepng1A4TcoI8X0LoO from "./images/cloudNativepng.png"; // plasmic-import: 1a4TCO-i8X0loO/picture
import microsoftTeamsImage17PngVfeWfttT62G0Jo from "./images/microsoftTeamsImage17Png.png"; // plasmic-import: VFEWfttT62G0JO/picture
import microsoftTeamsImage23Png6Nre34QebVlxdq from "./images/microsoftTeamsImage23Png.png"; // plasmic-import: 6Nre34QebVlxdq/picture
import microsoftTeamsImage18PngS20RtwjIAdYToN from "./images/microsoftTeamsImage18Png.png"; // plasmic-import: s20RtwjIAdYToN/picture
import oursYourspngB0NSkzbRm790Z from "./images/oursYourspng.png"; // plasmic-import: B0NSkzbRM79-0z/picture
import microsoftTeamsImage19PngDA51VtDGl0Bi3P from "./images/microsoftTeamsImage19Png.png"; // plasmic-import: dA51vtDGl0BI3p/picture

export type PlasmicTechnology__VariantMembers = {};
export type PlasmicTechnology__VariantsArgs = {};
type VariantPropType = keyof PlasmicTechnology__VariantsArgs;
export const PlasmicTechnology__VariantProps = new Array<VariantPropType>();

export type PlasmicTechnology__ArgsType = {};
type ArgPropType = keyof PlasmicTechnology__ArgsType;
export const PlasmicTechnology__ArgProps = new Array<ArgPropType>();

export type PlasmicTechnology__OverridesType = {
  root?: p.Flex<"section">;
  h2?: p.Flex<"h2">;
};

export interface DefaultTechnologyProps {
  className?: string;
}

function PlasmicTechnology__RenderFunc(props: {
  variants: PlasmicTechnology__VariantsArgs;
  args: PlasmicTechnology__ArgsType;
  overrides: PlasmicTechnology__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_new_habistack_com_css.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        plasmic_habistack_marketing_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column___2IbyK)}>
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2
          )}
        >
          {
            "Deploying applications to an enterprise-ready Azure environment has never been easier. "
          }
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ej5Pi
          )}
        >
          <React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#0091FF", fontWeight: 700 }}
            >
              {
                "Spend more time coding and testing than provisioning and deploying. "
              }
            </span>
            <React.Fragment>{"\n\n"}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ fontWeight: 700 }}
            >
              {"Fathym gives you a best practice, cloud-native workflow for"}
            </span>
            <React.Fragment> </React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ fontWeight: 700, color: "#0091FF" }}
            >
              {"rapid "}
            </span>
            <React.Fragment>{""}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#0091FF", fontWeight: 700 }}
            >
              {"application"}
            </span>
            <React.Fragment>{""}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ fontWeight: 700, color: "#0091FF" }}
            >
              {" development, testing and release"}
            </span>
            <React.Fragment>{". "}</React.Fragment>
          </React.Fragment>
        </div>

        <div className={classNames(projectcss.all, sty.columns__qy3Wv)}>
          <div className={classNames(projectcss.all, sty.column__nmwM)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__mxaeX)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage22PngFCmD4ZxRorQbig,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__pSaNy)}>
              <div className={classNames(projectcss.all, sty.column__xrFt9)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__e9BZs
                  )}
                >
                  {"Composable Application Development "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__k3Vpq
                  )}
                >
                  {"Future-proof"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__up35U
                  )}
                >
                  {
                    "Develop composable applications with modular frontends and microservices for agile and scalable application delivery. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__cXVeG)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__hcZmk)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xbXjK
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__cRMh)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__gyoJa)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage21PngJRtiyJu3WvOq3A,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__mrZB)}>
              <div className={classNames(projectcss.all, sty.column__fiTz6)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__eW4Ds
                  )}
                >
                  {"Built-In CI/CD "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jRrgW
                  )}
                >
                  {"Out-of-the-box"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iJl8V
                  )}
                >
                  {
                    "Automated build pipelines and source controls for no-code, hassle-free deployments. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__c9G3P)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__kOkth)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kB9
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__rJwo1)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__drYry)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: multiDatapngHM7CYgdgjrHxY,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__enXJe)}>
              <div className={classNames(projectcss.all, sty.column__sn0Ul)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___7UwwA
                  )}
                >
                  {"Application Governance  "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jDaoC
                  )}
                >
                  {"Easily version and spin off new apps"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e7SkU
                  )}
                >
                  {
                    "Consolidated control panel for hosting and managing your application portfolio."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__zGg0U)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__nCvYq)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fv3V4
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>

        <div className={classNames(projectcss.all, sty.columns__y6Bhd)}>
          <div className={classNames(projectcss.all, sty.column__ikTgc)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__x2IUx)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: cloudNativepng1A4TcoI8X0LoO,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__lUoLv)}>
              <div className={classNames(projectcss.all, sty.column___04Rgn)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__e3FJg
                  )}
                >
                  {"Best Practice Cloud Infrastructure "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fEpOt
                  )}
                >
                  {"Azure cloud"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__myMaG
                  )}
                >
                  {
                    "Automated, best practice, cost effective Azure cloud provisioning."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button___8DeXr)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__gi5K7)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bTye
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__viufg)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__jj6Rp)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage17PngVfeWfttT62G0Jo,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__xYnQ)}>
              <div className={classNames(projectcss.all, sty.column__pD7Yb)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__cnYhH
                  )}
                >
                  {"Our Cloud or Yours "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tzIb6
                  )}
                >
                  {"SaaS or Licensed"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zXYg
                  )}
                >
                  {
                    "Get started hassle-free in our SaaS cloud. Scale to a cloud hosted in your own Azure tenant for maximum control. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button___53U6W)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__ew4A)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gVe4F
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__fSnwR)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__mD8E)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage23Png6Nre34QebVlxdq,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__sZiYp)}>
              <div className={classNames(projectcss.all, sty.column__dyCp0)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__nGynX
                  )}
                >
                  {"Identity Management "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wDqEn
                  )}
                >
                  {"Custom SSO"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sBJp
                  )}
                >
                  {
                    "Authenticate users across your applications. Set up custom single sign-on (SSO)."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button___8Qx9)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__nAnq8)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1IK8T
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>

        <div className={classNames(projectcss.all, sty.columns__zAmDy)}>
          <div className={classNames(projectcss.all, sty.column__ms04U)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___30Lve)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage18PngS20RtwjIAdYToN,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__pZLlo)}>
              <div className={classNames(projectcss.all, sty.column__tIeLj)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__pm3Jp
                  )}
                >
                  {"Continuous Test and Release "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0C7F9
                  )}
                >
                  {"Streamlined UI"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9AAIa
                  )}
                >
                  {
                    "Accelerate development cycles. Fathym enables non-developers to easily test updates and ship to production when ready. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__vRbwx)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__pray5)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zrd6Z
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__elPZs)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___2XL2D)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: oursYourspngB0NSkzbRm790Z,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__ncXo)}>
              <div className={classNames(projectcss.all, sty.column__n09HA)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___7TxEx
                  )}
                >
                  {"Enterprise-Ready Security "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vFSos
                  )}
                >
                  {"Secure your IP"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lWo3
                  )}
                >
                  {
                    "Take advantage of Azure’s advanced security features. Secure your data ownership and intellectual property in your own Azure tenant."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__iaaBr)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__cDq3B)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4Uvyr
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__yNrtH)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__omOv9)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage19PngDA51VtDGl0Bi3P,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__dWeTg)}>
              <div className={classNames(projectcss.all, sty.column___9F3Gz)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__z8Xhc
                  )}
                >
                  {"Custom Workflows "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ewA77
                  )}
                >
                  {"Extensible"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eVhBt
                  )}
                >
                  {
                    "Fathym not only offers simplified workflows for releasing your applications to the cloud but gives you the ability to create your own custom workflows to accelerate your team. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__aQkxh)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__mg2Xr)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nb4B8
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTechnology__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTechnology__VariantsArgs;
    args?: PlasmicTechnology__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTechnology__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTechnology__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTechnology__ArgProps,
          internalVariantPropNames: PlasmicTechnology__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTechnology__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTechnology";
  } else {
    func.displayName = `PlasmicTechnology.${nodeName}`;
  }
  return func;
}

export const PlasmicTechnology = Object.assign(
  // Top-level PlasmicTechnology renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicTechnology
    internalVariantProps: PlasmicTechnology__VariantProps,
    internalArgProps: PlasmicTechnology__ArgProps
  }
);

export default PlasmicTechnology;
/* prettier-ignore-end */
